### ISSUE TITLE
handler timeout

### ISSUE THREAD

**Issue by monopollly** [nats-io/go-nats#240]
**OK**
```go
Subscribe("some", func(m *Msg) {
    Publish(m.Reply, data)
}

Request("some", data, 1000 * time.Millisecond)
```

**NOT OK**
```go
Subscribe("some", myhandler)

func myhandler(m *Msg){
   Publish(m.Reply, data)
}

Request("some", data, 1000 * time.Millisecond)
//nats: timeout here always
```

**WHY?)**

**Comment by mcqueary** [comment]
Hi, thanks for your interest in NATS. Your example doesn't give us much context to go on (i.e. would not be compilable as provided), but here are a couple of educated guesses: 

 *  A simple logic ordering issue, i.e. the call to `Subscribe()` is not completing before the `PublishRequest()` call inside of `Request()` has completed. This would be a common goroutine synchronization issue of some sort.

**OR, in the simpler case**

 * You're shadowing a global `nats.Conn` variable with a local variable, e.g.
```go
var nc *nats.Conn

func myhandler(m *nats.Msg) {
    log.Printf("Got message: '%s'", m.Data)
    nc.Publish(m.Reply, []byte("here is your reply"))
}

func main() {
    // BEWARE! This nc shadows the global because you used := vs. =
    nc, _ := nats.Connect("nats://localhost:4222")

    nc.Subscribe(subj, myhandler)

    msg, err := nc.Request("some", data, 1000 * time.Millisecond)
    if err != nil {
        log.Fatalf("Error: '%s'\n", err)
    } else {
        log.Printf("Got a reply: ", string(msg.Data))
    }
}
```

The `nc.Request()` call will time out, because although `myhandler` got the message, it doesn't have a valid `Conn`(because the global `nc` was never initialized) and its `Publish()` never executes. So, make sure you're using `=`, not `:=` to assign to `nc`.

If this doesn't help, please submit a short, compilable program/gist either here or on the natsio Google group.

**Comment by monopollly** [comment]
Thanks for answere!
sorry for abstract example;)

now I have this structure

```go
type API struct{
    App     string
    Host    string
    DB      *nats.Conn
    //here is nats handler
}

//connection function
func (a *API) Connect() (err error){
    a.DB, err = nats.Connect(a.Host)
    return
}

//make an instance
var api API

func main(){

   //connect is ok
   api.Connect()

   //subscribe is ok
   api.DB.Subscribe("help", func(m *nats.Msg) {
        api.DB.Publish(m.Reply, "help here")
    })
   
    //but this is timeout
    msg, err := api.DB.Request("help", []byte(`can you help?`), 1000 * time.Millisecond)
    println(msg.Data)
}
```

I thin this is one handler for nats or not?
What I missed?

Sorry for annoy)

**Comment by monopollly** [comment]
Thanks for answere! I got it!)
