### ISSUE TITLE
Bind to an interface channel not work?

### ISSUE THREAD

**Issue by thnt** [nats-io/go-nats#245]
```go
type Event interface {
	GetName() string
}

type event struct {
	name string
}

func (e event) GetName() string {
	return e.name
}

func main() {
	c, _ := nats.Connect(nats.DefaultURL)
	ec, _ := nats.NewEncodedConn(c, nats.JSON_ENCODER)

	in := make(chan Event)
	ec.BindRecvChan("events", in)

	out := make(chan Event, 10)
	ec.BindSendChan("events", out)

	out <- event{"test"}

	fmt.Println(<-in) // receive nothing here
}
```

**Comment by ColinSullivan1** [comment]
@thnt , Thank you for using NATS!

I appreciate your code snippet for this issue.  Underneath the NATS JSON encoder, we use the `encoding/json` package provided by go, which does not support unmarshalling JSON into an interface (interfaces have no underlying data structure).

If you add an error handler to the NATS connection:
```
	eh := func(_ *nats.Conn, _ *nats.Subscription, err error) {
		fmt.Printf("%v\n", err)
	}
	c, _ := nats.Connect(nats.DefaultURL, nats.ErrorHandler(eh))
```
You'll see this error message:
`nats: Got an error trying to unmarshal: json: cannot unmarshal object into Go value of type main.Event`

The easy solution is to reference your structure type instead of the interface.  Alternatively, you can encapsulate Event in a structure as a JSON.RawMessage, then later cast to an interface.  [Here](https://endophage.com/articles/golang-parse-to-interface/) is some information about using JSON with interfaces.
