### ISSUE TITLE
How do a test with the subscrition and publisher metods in the same file?

### ISSUE THREAD

**Issue by oscarvesga** [nats-io/go-nats#253]
Hi, I am try doing a test where I can prove the publish and subscribe of a message. I used a docker image `$ docker run -d --name $(NATS_NAME) -p $(NATS_PORT):4222 nats`

        import stan "github.com/nats-io/go-nats"

        URL := "nats://localhost:4222"
	sc, err := stan.Connect(URL)
	commons.Check(err)
	defer sc.Close()

	g := goblin.Goblin(t)
	g.Describe("ExecuteMutation", func() {
		g.It("Should subscrbe and publis a simple message", func() {
			i := 0
			sub, err := sc.Subscribe("input", func(m *stan.Msg) {
				i++
				t.Logf("[#%d] Received a message: %s\n", i, string(m.Data))
				assert.Equal(g, "string(m.Data)", "Hello World1", "should be the same")
			})
			commons.Check(err)
			defer sub.Unsubscribe()

			// Simple Synchronous Publisher
			sc.Publish("input", []byte("Hello World"))

		})

	})

In my test never is executed the subscribe function

**Comment by kozlovic** [comment]
It is a bit confusing since you use `stan` for `nats`, which as you may or may not know, `stan` is the code name for the nats streaming product (there is a `go-nats-streaming` repo) ;-)

Anyway, assuming that `commons.Check(err)` did not capture any error, I think that the problem is simple: you are sending a message and the function will return before the subscriber has a chance to receive it.
In your test function, use a channel to wait for the message. For instance:
```
    i:=0
    ch := make(chan struct{})
    sub, err := sc.Subscribe("input", func(m *stan.Msg) {
        i++
	t.Logf("[#%d] Received a message: %s\n", i, string(m.Data))
	assert.Equal(g, "string(m.Data)", "Hello World1", "should be the same")
        // Signal that we have received our message
        ch <- struct{}{}
    })
    commons.Check(err)
    defer sub.Unsubscribe()

    // Simple Synchronous Publisher
    sc.Publish("input", []byte("Hello World"))
    // Wait for message to be received
    select {
        case <- ch:
            // ok
        case <- time.After(2*time.Second):
            t.Fatal("Did not receive our message!")
    }
```
