### ISSUE TITLE
NATS single node guarantees?

### ISSUE THREAD

**Issue by rfw** [nats-io/go-nats#256]
Hi all,

I'm wondering if, in a single node setup of NATS, the following guarantees hold:

- a publisher will be notified if they failed to publish a message if their Flush() operation failed (the publisher will know if their connection was interrupted to NATS during publish)

- a subscriber will always receive a Flush()ed message or encounter a connection error (the message may be lost, but the subscriber will know it is lost)

I understand NATS only has at-most-once delivery guarantees, but I am wondering if it has these "once-or-error" semantics when running as a single node – and if not, under what scenarios will this assumption be violated.

**Comment by mcqueary** [comment]
Hi,

Flush() sends a PING to the server, forces a flush of the underlying
buffered TCP connection, and awaits a PONG response, thus ensuring that any
previously buffered messages on the connection have been sent to the
server. An error is generated if no PONG is received within the timeout
period (default 60s in most clients - use FlushTimeout() if you want to
tweak that).

So yes, if Flush() succeeds, the message will have made it to the server
successfully. If Flush() fails, you have no such guarantee, although
technically it’s still possible the message made it, but the PING didn’t.

On the subscriber side, the subscriber should receive the message if it is
not a “slow consumer” (i.e. it’s servicing its connection — draining
messages —  in a timely fashion). If the subscriber is deemed a slow
consumer by NATS, messages may be lost or the connection may be dropped.
The client will not be notified that a specific message has been dropped,
however, since NATS messages have no uniquely identifynig info (unlike NATS
Streaming).

If you want to be notified of a slow consumer problem, register an async
error handler for your connection; this error handler (callback) will be
invoked when a slow consumer problem is encountered.

Make sense?

-Larry

On January 25, 2017 at 1:42:35 AM, rfw (notifications@github.com) wrote:

Hi all,

I'm wondering if, in a single node set up of NATS, if the following
guarantees hold:

   -

   a publisher will be notified if they failed to publish a message if
   their Flush() operation failed (the publisher will know if their connection
   was interrupted to NATS during publish)
   -

   a subscriber will always receive a Flush()ed message or encounter a
   connection error (the message may be lost, but the subscriber will know it
   is lost)

I understand NATS only has at-most-once delivery guarantees, but I am
wondering if it has these "once-or-error" semantics when running as a
single node.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/nats-io/go-nats/issues/256>, or mute the thread

**Comment by ColinSullivan1** [comment]
@rfw, Thank you for your interest in NATS!

Regarding the `Flush()` operation, should the server goes down as you are calling flush, you'll get a connection error (`ErrInvalidConnection`, `ErrConnectionClosed`), or a timeout error (`ErrBadTimeout`).  Note, this indicates the flush may have failed, not necessarily that it did with respect to what happens in the server.

Flushing does not guarantee a message will be received by a subscriber.  From the producer side, a successful flush only indicates that the server has received the message, not that subscribers have received it.  Consider the case where the server has received the published message, buffered the message to send to the subscriber, and has responded to the producer's flush, but is terminated before the message can be sent to the subscriber.

To achieve a guarantee for your application, I suggest you check out NATS streaming, or you can verify through request/reply that all of your data has been received.

Can you share more of your use case?

Thanks,
Colin

**Comment by rfw** [comment]
Hi Colin and Larry,

Thanks for your replies. My use case is to optimistically broadcast updates of my data store to subscribers – I don't care if messages are lost or really even received out of order, I just need to make sure that if a message was lost, the client can resubscribe and also re-fetch the latest state of all data they're interested in from the store.

If the server was terminated before the message was sent to the subscriber, would the subscriber know that the server was terminated and therefore they would have missed an update?

NATS streaming seems a little overkill for the guarantees I need – I don't particularly need persistence, durability, or replay here.

**Comment by ColinSullivan1** [comment]
@rfw, Absolutely, happy to help!

> If the server was terminated before the message was sent to the subscriber, would the subscriber know that the server was terminated and therefore they would have missed an update?

Yes, the subscriber can detect a broken connection through callbacks setup on the NATS connection:
```go
// Setup callbacks to be notified on disconnects, reconnects and connection closed.
nc, err = nats.Connect(servers,
    nats.DisconnectHandler(func(nc *nats.Conn) {
        fmt.Printf("Got disconnected!\n")
    }),
    nats.ReconnectHandler(func(_ *nats.Conn) {
        fmt.Printf("Got reconnected to %v!\n", nc.ConnectedUrl())
    }),
    nats.ClosedHandler(func(nc *nats.Conn) {
        fmt.Printf("Connection closed. Reason: %q\n", nc.LastError())
    })
)
```
In your case, this should be very straightforward - when a reconnect handler is invoked, you know there was an interruption of service, but the connection has been re-established, and you can then fetch any missing data.

**Comment by rfw** [comment]
Perfect, thanks for your help!
