### ISSUE TITLE
Async handler/callback blocks

### ISSUE THREAD

**Issue by Ulexus** [nats-io/go-nats#263]
I expect, when defining a handler, that each execution of the handler will be performed in a goroutine (as, for instance, http handlers are).  Instead, the execution of the handler [blocks its subscription until it returns](https://github.com/nats-io/go-nats/blob/master/nats.go#L1449).

Due to the variable `nats.Handler` signatures, trying to wrap such a handler in a goroutine with middleware is rather cumbersome... moreso since the utilities for matching and manipulating these various types are not exported.

There are no return values for the handler, so I'm failing to see a _reason_ for not executing the handler in a goroutine... but perhaps I am missing something?

**Comment by Ulexus** [comment]
Upon further consideration, I believe the current implementation is the correct implementation.  Unlike a web server and web proxy setup, NATS' subscription system is highly reflexive of flow control, and forcing the handler to control flow in that way is a supremely useful feature.

I think it would be useful to document this design intent in some way (at least, that is more obvious that my feeble efforts discovered), but I think this issue is a feature, not a bug.

**Comment by mcqueary** [comment]
Another reason we have implemented it this way is ordering. Forcing a
single goroutine to execute the handler as each message is received on the
connection ensure sequential order of processing, which would NOT be
guaranteed if each invocation occurred in its own handler.

Of course, if you don't care about ordering, and have potentially
long-lived handler logic, you can always  spawn a goroutine per message
yourself.

We will document this better. Thanks for raising this issue.

**Comment by Ulexus** [comment]
Another good point, yes.  Thanks!

**Comment by pamelin** [comment]
Has this actually been actioned?

I get the point of flow control however if we are calling something async it means I don't care about ordering. Calling it async is very misleading as I've seen the same issue raised by few people. Blocking/Non blocking is more true reflection of the behaviour.

**Comment by kozlovic** [comment]
It's called async as opposed to the sync APIs in which you need to call NextMsg() to get the next available message. The async subscription means that the callback is called whenever a message is available, but one message at a time for a given subscription. You are free to invoke the processing of the message in a go routine instead of directly process this message in the message callback.

**Comment by pamelin** [comment]
Hey Ivan, thank you for your reply.

I do get your point, however as per previous poster mentioned it took a bit digging to find out what async means in this context.

My main question was: has documentation been updated to reflect this?

I'm happy to contribute back with addition of new methods which will invoke every handler in the separate go routine as per original post. I understand that it is easy to run go routine yourself however if your handler is of type nats.Handler this becomes a bit cumbersome as per original poster.

**Comment by MohanGyara** [comment]
how to block natsSubscription_NextMsg call? I see there is timeout but want to block this call until there is a message for the subscription.

**Comment by kozlovic** [comment]
@MohanGyara Your question is not really related to this original issue, so it would have been best to create a new issue.

Regardless, if you really want to have the subscription run until message becomes available, then why use the synchronous subscription instead of async? You should use Conn.Subscribe() and provide a callback that will be invoked when messages are available.

Otherwise, you can use a very high timeout. How high depends on your needs. You could set to 1 hour, 1 year, etc..
