### ISSUE TITLE
death lock problem

### ISSUE THREAD

**Issue by ZhiqinYang** [nats-io/go-nats#277]
i wrote a test like this : 
  
    last := time.Now()
    var cnt int64
    var wg sync.WaitGroup
    nc, err := nats.Connect(nats.DefaultURL)
    if err != nil {
        log.Fatal(err)
    }
    ec, err := nats.NewEncodedConn(nc, nats.JSON_ENCODER)
    if err != nil {
        log.Fatal(err)
    }
    defer ec.Close()
    sendCh := make(chan []byte)
    ec.BindSendChan("test", sendCh)
    recvCh := make(chan []byte)
    ec.BindRecvChan("test", recvCh)
    var a = make([]byte, 64*1024)

    // sender
    go func() {
        for i := 0; i < 50000; i++ {
            wg.Add(1)
            sendCh <- a
        }
    }()

    for i := 0; i < 50000; i++ {
        go func() {
            defer wg.Done()
            <-recvCh
            atomic.AddInt64(&cnt, 1)
        }()
    }
    wg.Wait()

the nats server logs :[1] 2017/04/15 09:58:14.204417 [INF] 172.17.0.1:46610 - cid:6 - Slow Consumer Detected
and my test is deathlock  
how can i solve this problem ?

**Comment by kozlovic** [comment]
@ZhiqinYang I see several issues with your test program, but what is mainly happening as you point out from the server's log file, is that the consumer is not consuming fast enough. When this happens, the server closes the client connection. Even if the client library reconnects, it may have missed some messages which may cause your client to wait indefinitely (since you add to the wait group).
Here are few things I would like to point out:

- You are not using a buffered channel for the receiver. It means that when the client library gets a message and tried to put it into the channel, if there is no room, the message is going to be dropped. Add an AsyncError handler and your application could be notified that this happened.
- You are creating 50,000 go routines for the receiving side. Is this really something you intended to do?
- The first wg.Add() is happening in a go-routine, so there could be a race where wg.Wait() is called before (or at the same time, causing a panic) the first call to.wg.Add() is done.

Note that I used your test program and could run it without issue on my machine (well not with `-race` since there is a limit of 8192 go routines), but I could see why you could have problems. Try to use a buffered channel for `recvCh`, and I don't think you need a go routine per received message. Also, add the async error handler to see if the client library is dropping messages. If it does, and since you call wg.Add() for each sent message, there won't be the same number of wg.Done(), so your application will appear to hang, but really is just due to the fact that the wait group was not decremented.

If you still have an issue, please send the stack trace when your application hangs.
