### ISSUE TITLE
No reconnect after receiving error from server

### ISSUE THREAD

**Issue by markuslindenberg** [nats-io/go-nats#296]
I ran into this problem when the client tries to subscribe to an invalid subject using an EncodedConn:

```
	_, err = c.Subscribe("test.foo..bar", handler)
	log.Println(err)
```

`err` is `nil`, but the server will reply with
```
-ERR 'Invalid Subject'
```

## Result

The connection is closed and the DisconnectHandler is triggered. The client does not try to reconnect.

## Expected result

I would expect the client to either not disconnect because a single subscribe failed or immediately reconnect and resubscribe.

Random observation: Publishing to an 'Invalid Subject' doesn't throw an error.

**Comment by kozlovic** [comment]
In NATS, most of operations are asynchronous. For instance, even the `Subscribe()` call is sending a protocol to the server, but not synchronously receiving a response from the server. This call may still return an error (say the connection is closed, etc..). The server is sending this error asynchronously.

When the connection is closed, and disconnect or closed handler is invoked, you could call Conn.LastError() and you would see that the reason is an invalid subject.

Reconnecting for such error would not make sense since the subscribe protocol would be resent and connection will be closed again, etc...

**Comment by markuslindenberg** [comment]
OK, I see. 

I'm facing this problem in a small REST<->NATS gateway I implemented for my application. It allows legacy services some limited interaction with NATS using HTTP, like broadcasting to a given subject. I'd rather have the gateway not be disconnected from NATS for avoidable errors like 'Invalid Subject'.

I guess 'Invalid Subject' is a (or the only?) server error that is entirely predictable. I could check the subject's validity in my application logic before publishing.  
Would it be an option to have a client-side check for invalid subjects inside go-nats, so that `Publish()` to invalid subjects will return a synchronous error?

**Comment by kozlovic** [comment]
@markuslindenberg We could potentially, but the server is already doing the check. It may not make sense to copy the check code in all clients. You have to ask yourself: what your application would do differently if it got an `Invalid Subject` error when calling `Subscribe()`? It is likely a configuration error and the application will probably have to stop, right? (it can't simply ignore). That's basically what happen now if you register your closed callback, you can check last error and exit the application. What are your thoughts?

**Comment by kozlovic** [comment]
@markuslindenberg Alternatively, you could, after the `Subscribe()` call, issue a call to `Conn.Flush()`. This sends a PING to the server and waits for a PONG. Since this is the same tcp connection, it guarantees that the SUB protocol message will be processed by the server and if the server sent an error back, it would be before the PONG. Therefore, after the `Flush()` call, you could then check for `Conn.LastError()` in place. If the server sent an `Invalid subject`, you should get it there. Let me know if this works for you.

**Comment by markuslindenberg** [comment]
The problem is that still the nats client will disconnect. I don't have the problem in most of my microservices because, as you said, an invalid subject is a configuration/implementation error. But in this special case I'm running a RESTful service that does requests to arbitrary subjects on behalf of other services, so the service is not in control of the subject and I'm multiplexing lots of (changing) subscriptions into one NATS connection, so I don't want to interrupt all requests waiting for a reply because one HTTP client supplied me with an invalid subject.

As this is one special case of error that is (mostly) a problem in this special use case, I'm getting more convinced that I'll just validate the subject I'm supposed to publish to in my application logic and reject invalid subjects before trying to publish.

**Comment by markuslindenberg** [comment]
@kozlovic Thanks for your insights, very helpful and very much appreciated. :)

**Comment by kozlovic** [comment]
Closing this issue since we agreed that no change would help here and that it is best for the user to do a flush and check `LastError()` to ensure that there was not an invalid subject.
