### ISSUE TITLE
v1.2.2 and nats -> go-nats rename.

### ISSUE THREAD

**Issue by mdevan** [nats-io/go-nats#301]
Release v1.2.2 is basically broken because of the nats -> go-nats rename. The old repo ("github.com/nats-io/nats") is imported at many places in production, test and example code of v1.2.2. It is not possible to build even the examples under https://github.com/nats-io/go-nats/tree/master/examples against v1.2.2.

Commits c1c9ec3 and 6b6bf39 probably fix the problem. Is it possible to make a new release?

Thanks!

**Comment by kron4eg** [comment]
Yeah, I saw surprised to find

    vendor/github.com/nats-io/go-nats/
    vendor/github.com/nats-io/nats/

in vendor directory o_O

**Comment by kozlovic** [comment]
@mdevan We are definitively due for a release ;-) Hopefully, we will do that very soon. We have added new APIs and fixed some defects, so it will likely be a `1.3.0` release version. I will let you know asap.

@kron4eg Not sure which vendor directory you are referring to here?

**Comment by kron4eg** [comment]
@kozlovic oh it was vendor from my project, that was rendered by `dep`. In my code I've imported "github.com/nats-io/go-nats" and run `dep`, it picked up latest available release and in that release "github.com/nats-io/nats" imports are also used, so I end up with two versions of nats :D

**Comment by eicca** [comment]
I can second the problem.
By default https://github.com/golang/dep will vendor the latest release `1.2.2` which has (had) the problem importing `github.com/nats-io/nats/`. Because of this `dep` will also vendor old version of the library. And because of this `goimports` will be confused about the importing the library :)

It would be great if you can release a new version of `go-nats` in near future.

Of course, it's totally possible to point to a specific revision as a workaround for the time being.

**Comment by kozlovic** [comment]
We have released v1.3.0! https://github.com/nats-io/go-nats/releases/tag/v1.3.0
Hope this fixes dep issues. Thanks!
