### ISSUE TITLE
permissions violation on subscribe and client reconnect issues

### ISSUE THREAD

**Issue by valichek** [nats-io/go-nats#330]
First issue - there are no err returned from `nc.QueueSubscribeSync` or `nc.SubscribeSync` when getting permissions violation on subscription, I can catch it only with `nc.SetErrorHandler`

Second issue - when server connection is broken after `permissions violation` on subscription and client will reconnect it will try to subscribe on violated subscription. The reason is that client doesn't remove subscription from the list when getting the `permissions violation` error

**Comment by kozlovic** [comment]
This is the way the protocol was designed. Most communication with the NATS Server is asynchronous. Creating the subscription will not return an error in place (unless connection is already closed for instance).

As you could see, you would receive a notification through the async callback. Another way can be to follow the subscribe call with a `nc.Flush()` so that the `nc.LastError()` is updated with the error that server sent for the subscribe call. Note that this would work only if you are not using that same connection in parallel that could produce a different error. What I mean is that then `nc.LastError()` may not be the error caused by the subscribe call but some other error that occurred with this connection.

The subscription is not removed because the server is simply returning a text error message and there is no reference to the subscription causing the error.

You could decide to close the connection and recreate should you get permission violation. For some users, this could/should be treated as a fatal error. For others, since permission could be changed in the server, they may want to have their application still running.

**Comment by valichek** [comment]
Yes, it's clear about async. But if server includes subscription name caused the error it would be possible to identify it. Or should I create the issue for the server?

**Comment by kozlovic** [comment]
Server would need to send that info for the client to be able to remove. I don't think there are plans to modify the protocol at this point though.

**Comment by valichek** [comment]
@kozlovic I just checked that server adds the subscription subject to the error. So no problem here.

**Comment by kozlovic** [comment]
subject is not enough. There would be a need for subscription id because an application could easily have several subscriptions on the same subject (granted that permission would then be probably cause error for all of them - unless changes are made dynamically on the server).

**Comment by kozlovic** [comment]
@valichek The point is that you either do not want your application to proceed if there was a permission violation when creating it (either you fatal on async error callback or use the Flush() approach), or you don't mind and in this case it should not matter that the subscription is resent on reconnect (and failed again, or possibly not if the permission is changed in the server).
