### ISSUE TITLE
Unsubscribing from Subscriptions list based on Sid

### ISSUE THREAD

**Issue by ynkumar143** [nats-io/go-nats#332]
I need to unsubscribe from list of subscriptions with the same topic based on ssid of subscription made. Similar functionality done by node-nats but not with go-nats.

**Comment by kozlovic** [comment]
Not sure what you mean here. In Node.js, the returned object when creating a subscription is an id, but in Go, you have a Subscription object returned, which you then would use to `Unsubscribe()`.

For instance create a subscription calling this: https://github.com/nats-io/go-nats/blob/master/nats.go#L2154
Then you can unsubscribe calling this: https://github.com/nats-io/go-nats/blob/master/nats.go#L2313

**Comment by ynkumar143** [comment]
Can you please at this program where i created a use case for the scenario i am explaining. 
https://github.com/ynkumar143/Go_Practice/blob/master/Unsub_Case.go

The output of this program is below. 
> Subscribing for Topic: Tree.Branch
> SID Of First Subscription: 1
> Subscribing for Topic: Tree.Branch
> SID Of Second Subscription: 2
> Message Publishing on Topic: Tree.Branch
> Message Received  on Topic: <-- Tree.Branch 
> Message: Information
> To URL: http://localhost:8080/FirstApi
> Message Received  on Topic: <-- Tree.Branch 
> Message: Information
> To URL: http://localhost:8001/SecondApi
> Subscription Information Before Unsubscribing map[1:0xc420100000 2:0xc4201100c0]
> Unsubscribing from Topic Tree.Branch
> Subscription Information after Unsubscribing map[2:0xc4201100c0]

However, I achieved to unsubscribe from Topic of first subscription. But this is indirect and I am sending some message information that is occupying bytes in my channel connection. I am thinking for an alternate solution to unsubscribe just based on sid of subscription list.

**Comment by kozlovic** [comment]
@ynkumar143 I have reviewed your test program and I am not clear of few things:
- Is it a requirement to have a message published so that you unsubscribe from the message callback? If not, when subscribing, keep a reference to the subscription (right now you are not saving it) and use that to unsubscribe from any place in your code.
- If you need to send an "unsubscribe" message on the subject, and you want to target a specific subscription, you could send an ID that you could generate when creating the subscription, and make sure that the unsubscribe message's ID matches the ID of the subscription that you close on with the handler.

Note: Your current way of unsubscribing does not look right. But for information, your use of `unsub_req` is not thread safe. You set it without locking when sending the unsubscribe message and check it - without locking - in the subscription message callback. Also since you have more than one subscription, the message handler code could be executed in parallel, so you could have 2 data races: one between the UnsubscribeTopic() function and the handler, and one between the handlers themselves.

**Comment by ynkumar143** [comment]
@kozlovic It is not requirement to send "Unsubscribe" in publish message. I am trying to use only NATS package without storing information. I have tried 1st Option to save the subscription details for every subscription(Used Map Data structure). But the point is, why I need to use memory to store them when NATS is already storing that information. (My Subscriptions list is more and expectation of 50000). In this case, I guess that is not a good idea to store subscription information. 

If i find a solution of not storing subscription information and process it using facilities of nats package. I will not go for the procedure of sending "unsubscribe" in publish message. 

My thought is " I can get the Subscription ID from  NATS whenever a topic is subscribed and save this in Database mapping to user information. At the time user is unsubscribing, I will retrieve the sid of subscription from Database and pass it to the Unsubscribe function of Nats from anywhere in my project". 

To store Subscription details in Database(in my case MongoDb) it will not accept all type of data to store in it. In case if I am not using database and storing subscription info in map data structures, in production if the project is restarted  i will use all my subscription details. 

Thanks for Note,  I will take care in production code.

**Comment by kozlovic** [comment]
@ynkumar143 What is not clear, is how you decide in your application which subscription to unsubscribe?

If it is based on some information that you got when creating it, you would still need to keep some sort of binding between the information that caused your application to create the subscription and the subscription itself. For instance, with your example code, I would simply keep a reference of `sub` (a `*nats.Subscription`) that you get from this call: `sub, err := nc.Subscribe()`, into the `userInfo` (assuming that there is one subscription only per user. Then you can call `userInfo.sub.Unsubscribe()`.

But again, it is too unclear to me how you want to create subscriptions and unsubscribe them, so my comments may not be relevant.

**Comment by ynkumar143** [comment]
@kozlovic I written a program which is saving subscription information reference and using it to unsubscribe from anywhere in program. This can be seen in below program. 

1st Case: https://github.com/ynkumar143/Golang/blob/master/Unsub_Save_Subscription.go

But the solution i was trying to explain is written in below program. I thought Instead of saving subscription information references we can save the subscription id in structure and pass it in Unsubscribe function of nats package. (This was not supported in nats).  `savednatConnect.nats_connct.**UnSubscribeWithSID**(userTwoInfo.sid)`. 

2nd Case: https://github.com/ynkumar143/Golang/blob/master/Unsub_based_sid.go

My Suggested Code change in nats package : 

```
func (nc *Conn) UnSubscribeWithSID(sid int64) error {
	s := nc.subs[sid]
	return s.Unsubscribe()
}

```
I have tested and working fine. 

Now after going through memory usages the memory used in 1st case is 4 bytes for 32bit systems and 8 bytes for 64bit. But wanted to understand the reason why we cannot include an extra function in go-nats package just passing sid of subscription instead of subscription information.

**Comment by kozlovic** [comment]
Because the `Unsubscribe()` is a receiver of the `Subscription` object. Once you create a subscription (from the connection), all subscription related functions are tied to that subscription. This is object oriented model.
In order to have a `Conn.UnsubscribeWithSID()` as you suggest, we would also need to expose the subscription ID. But again, I see no value since in any case you would have to store either the SID or the subscription, which is same size (in 64bit platforms, and SID actually bigger in 32bit platforms).
