### ISSUE TITLE
Conditions for Publish

### ISSUE THREAD

**Issue by anastop** [nats-io/go-nats#337]
Hi, 

I am wondering which are the conditions for `Publish` to properly deliver a message to subscribers listening on the same topic. Based on a few experiments, I observe that delivery may succeed or not depending on what follows after the call to `Publish`.

To be more clear, I am experimenting with the basic example below:  

```go
// Publisher
func main() {
	nc, err := nats.Connect("nats://localhost:4232")
	if err != nil {
		log.Fatal(err)
	}

	err = nc.Publish("foo", []byte("Hello World"))
	if err != nil {
		log.Fatal(err)
	}
	nc.Close()
}
```

```go
// Subscriber
func main() {
	done := make(chan bool)
	nc, err := nats.Connect("nats://localhost:4232")
	if err != nil {
		log.Fatal(err)
	}
	defer nc.Close()

	nc.Subscribe("foo", func(m *nats.Msg) {
		log.Printf("Received: %s\n", string(m.Data))
	})
	<-done
}
```

In the above code, if I omit `nc.Close()` at the end of the publisher code the message will be never delivered to the subscriber. In fact, it does not even manage to reach the NATS server. So my initial guess was that one might have to call `Close` no matter what. However, if I use other statements in place of `nc.Close()` (e.g. if I log a message or wait on a "done" channel), the program behaves again correctly, with the message getting delivered to the subscriber.

Is this behavior expected? Does it have to do with timing? 

My Go version is 1.9.2.

**Comment by kozlovic** [comment]
@anastop Most of NATS API are asynchronous. Publish() is no different. This call is adding the content to a buffer that is flushed asynchronously (it is possible that the buffer is flushed during the call if the content does not fit, etc..). So what is happening is that your application exits abruptly and therefore the routine flushing the connection buffer has not a chance to execute.
You should use `nc.Flush()` instead of `Close()` to ensure that your message has reached the server. I am not saying that you should call `Flush()` after every publish though, performance would suffer. I am just saying that in the above example, it would ensure that the server did receive the message before the application exits.

**Comment by anastop** [comment]
thanks! this is pretty clear now.
