### ISSUE TITLE
Why conn.waitForMsgs(async mode) use lock+cond+list instead of Channel?

### ISSUE THREAD

**Issue by MaruHyl** [nats-io/go-nats#428]

**Comment by wallyqs** [comment]
Because it is more memory efficient. By default async subscribers have a queue of up to 65536 pending messages (`DefaultSubPendingMsgsLimit `) so using a linked list is better in this case than allocating a buffered channel of the same size, instead letting memory grow/decrease dynamically as messages are received and processed.
